### ISSUE TITLE
[1.17] Dark Forest

### ISSUE THREAD

**Issue by Khytwel** [teamauroramods/EnhancedMushrooms-Fabric#13]
There is a small generation bug with Enhanced Mushrooms in 1.17, the trees and mushrooms of the Dark Forest are not generated anymore.

![image](https://user-images.githubusercontent.com/54046029/122618479-a198a100-d08e-11eb-9d1d-a46ca6029e72.png)

**Comment by mosharky** [comment]
I have the same issue

**Comment by Quizer9O8** [comment]
Yep, I also do have this issue. I hope it get fixed next update.
