### ISSUE TITLE
Mushroom Sign Crash

### ISSUE THREAD

**Issue by VaelophisNyx** [teamauroramods/EnhancedMushrooms-Fabric#14]
[latest.log](https://github.com/teamauroramods/EnhancedMushrooms-Fabric/files/6713416/latest.log)
log file of crash; seems to be a rendering error from a typo?

**Comment by JustinPlayzz** [comment]
So we can't reproduce this, can you provide a _crash report_ cause its a log?

**Comment by VaelophisNyx** [comment]
Can try, I suppose. Hold on

**Comment by VaelophisNyx** [comment]
[crash-2021-06-30_04.50.51-client.txt](https://github.com/teamauroramods/EnhancedMushrooms-Fabric/files/6740231/crash-2021-06-30_04.50.51-client.txt)

**Comment by sgage13** [comment]
[crash-2021-08-16_22.43.02-client.txt](https://github.com/teamauroramods/EnhancedMushrooms-Fabric/files/6997122/crash-2021-08-16_22.43.02-client.txt)
Having the same issue as well
