### ISSUE TITLE
Mushroom logs dont drop anything

### ISSUE THREAD

**Issue by sleepingdragoninn** [teamauroramods/EnhancedMushrooms-Fabric#3]
![image](https://user-images.githubusercontent.com/55819817/115701495-32af0c80-a3ab-11eb-81a8-c89d4a6970c2.png)

Can't really provide too much detail for this one

**Comment by JustinPlayzz** [comment]
We forgot to add the loot tables, there is a issue for this all ready so I will close this one sorry for the inconvenience.
