### ISSUE TITLE
Mod incompatibility: Promenade

### ISSUE THREAD

**Issue by saltyseadoggo** [teamauroramods/EnhancedMushrooms-Fabric#7]
When this mod is loaded alongside [Promenade](https://www.curseforge.com/minecraft/mc-mods/promenade), the latter's new mushroom types cannot be grown into their huge variants using bone meal. The player can use bone meal on the mushrooms and it is consumed and produced particles, but nothing else happens. This works correctly without Enhanced Mushrooms loaded, which means that EM is breaking this feature.

**Comment by Steven-Baez** [comment]
I’m making an issue over Promenade

**Comment by Steven-Baez** [comment]
Alright I looked into it and its actually our problem due to how the MushroomPlantBlockMixin is

**Comment by JustinPlayzz** [comment]
fixed in #20
